version: '2.2'

networks:
    woodynet:
        external: true

services:
    db:
        build: ./database
        container_name: woodysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        networks:
            woodynet:
                ipv4_address: 172.18.0.2
        security_opt:
            - apparmor=docker-default
        mem_limit: 1024m
        mem_reservation: 256M
        cpus: 1   
        # Le paramètre cpu n est pas pris en compte par docker compose il faut l entrer manuellement avec docker update --cpus 1 CONTAINER

    web:
        build: ./web
        container_name: woodyweb
        ports:
          - 8080:80
        networks:
            woodynet:
                ipv4_address: 172.18.0.3
        security_opt:
            - apparmor=docker-httpd-restricted
        mem_limit: 512m
        mem_reservation: 256M
        cpus: 1
         