version: '3'

services:
    db:
        build: ./database
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1024M
                    pids: 100
                reservations:
                    cpus: '0.5'
                    memory: 256M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
        container_name: woodysql
        healthcheck:
            test: mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD status || exit 1
            interval: 60s
            retries: 1 
            start_period: 20s
            timeout: 20s
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - type: volume
              source: woodydata
              target: /var/lib/mysql
        networks:
            woodynet:
                ipv4_address: 172.18.0.2
        #security_opt:
            #- apparmor=docker-default
            

    web:
        build: ./web
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                    pids: 100
                reservations:
                    cpus: '0.25'
                    memory: 256M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
        container_name: woodyweb
        ports:
          - 8080:80
        links:
          - fluentd
        logging:
          driver: "fluentd"
          options:
            fluentd-address: "172.18.0.4:24224"
        healthcheck:
            test: curl --fail http://localhost:80 || exit 1
            interval: 60s
            retries: 1
            start_period: 20s
            timeout: 10s
        networks:
            woodynet:
                ipv4_address: 172.18.0.3
        security_opt:
            - apparmor=docker-httpd-restricted
        
    fluentd:
        build: ./fluentd
        volumes:
            - ./fluentd/conf:/fluentd/etc
            - /var/log/:/fluentd/log/
        environment:
            - FLUENT_ELASTICSEARCH_HOST=172.18.0.5
            - FLUENT_ELASTICSEARCH_PORT=9200
            - FLUENT_ELASTICSEARCH_SCHEME=http
        links:
            - "elasticsearch"
        ports:
            - "24224:24224"
            - "24224:24224/udp"
        networks:
            woodynet:
                ipv4_address: 172.18.0.4
    
    
    elasticsearch:
        image: elasticsearch:7.10.0
        container_name: elasticsearch
        environment:
            - node.name=elasticsearch
            - cluster.name=docker-cluster
            - discovery.seed_hosts=elasticsearch
            - cluster.initial_master_nodes=elasticsearch
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        expose:
            - "9200"
        ports: 
            - "9200:9200"
        volumes:
            - type: volume
              source: elasticsearch_data
              target: /usr/share/elasticsearch/data
        networks:
            woodynet:
                ipv4_address: 172.18.0.5

    kibana:
        image: kibana:7.10.0
        environment:
          - ELASTICSEARCH_URL=http://172.18.0.5:9200
        links:
            - "elasticsearch"
        ports:
            - "5601:5601"
        networks:
            woodynet:
                ipv4_address: 172.18.0.6 


networks:
    woodynet:
        ipam:
            config:
                - subnet: 172.18.0.0/24

volumes:
    woodydata:
    
        
            