version: '3'

services:
    db:
        build: ./database
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 1024M
                    pids: 100
                reservations:
                    cpus: '0.5'
                    memory: 256M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
        container_name: woodysql
        healthcheck:
            test: mysqladmin -u$MYSQL_USER -p$MYSQL_PASSWORD status || exit 1
            interval: 60s
            retries: 1 
            start_period: 20s
            timeout: 20s
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - type: volume
              source: woodydata
              target: /var/lib/mysql
        networks:
            woodynet:
                ipv4_address: 172.18.0.2
        security_opt:
            - apparmor=docker-default
            

    web:
        build: ./web
        deploy:
            resources:
                limits:
                    cpus: '1'
                    memory: 512M
                    pids: 100
                reservations:
                    cpus: '0.25'
                    memory: 256M
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 5
        container_name: woodyweb
        ports:
          - 8080:80
        healthcheck:
            test: curl --fail http://localhost:80 || exit 1
            interval: 60s
            retries: 1
            start_period: 20s
            timeout: 10s
        networks:
            woodynet:
                ipv4_address: 172.18.0.3
        security_opt:
            - apparmor=docker-httpd-restricted

    grafana:
        image: grafana/grafana:latest
        ports:
        - 3000:3000
        environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=password
        volumes:
        - grafana-data:/var/lib/grafana
        networks:
            woodynet:
                ipv4_address: 172.18.0.4

    loki:
        image: grafana/loki:2.7.1
        ports:
        - 3100:3100
        command: -config.file=/etc/loki/loki-config.yml
        volumes:
        - loki-data:/data
        networks:
            woodynet:
                ipv4_address: 172.18.0.5

    promtail:
        image: grafana/promtail:master
        ports:
        - 3101:3101
        volumes:
        - /var/log:/var/log
        - promtail-data:/data
        command: -config.file=/etc/promtail/promtail-config.yml
        networks:
            woodynet:
                ipv4_address: 172.18.0.6

networks:
    woodynet:
        ipam:
            config:
                - subnet: 172.18.0.0/24

volumes:
    woodydata:
    grafana-data:
    loki-data:
    promtail-data:
    
        
            