name: Vulnerability Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Scan vulnerabilities
        uses: actions/aquasecurity/trivy-action
        with:
          args: --exit-code 0 --severity CRITICAL https://github.com/QuentinServais/DockerSecurity/blob/main/docker-compose.yaml
