name: Vulnerability Scan

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
              
      - name: Install trivy
        run: |
            apt-get update
            apt-get install -y apt-transport-https
            curl -s https://packagecloud.io/install/repositories/aquasecurity/trivy/script.deb.sh | bash  

      - name: Scan configuration
        run: trivy --exit-code 0 --severity CRITICAL,HIGH --config .